# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0002_auto_20161021_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('traveldate_from', models.DateTimeField()),
                ('traveldate_to', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myschedule', to='belt_app.User')),
            ],
        ),
    ]
