# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0003_travelschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelschedule',
            name='traveldate_from',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='travelschedule',
            name='traveldate_to',
            field=models.CharField(max_length=10),
        ),
    ]
