# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0004_auto_20161021_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelschedule',
            name='traveldate_from',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='travelschedule',
            name='traveldate_to',
            field=models.DateField(auto_now_add=True),
        ),
    ]
