# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0006_auto_20161021_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelschedule',
            name='join',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='joined_user', to='belt_app.User'),
            preserve_default=False,
        ),
    ]
