# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0007_travelschedule_join'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelschedule',
            name='join',
        ),
    ]
